### ISSUE TITLE
Undefined array key "docgroups"

### ISSUE THREAD

**Issue by zloyxrom** [exdis/modx#1]
При изменение tv появляются ошибки
Warning: Undefined array key "docgroups" in /manager/processors/save_tmplvars.processor.php on line 223

Warning: Cannot modify header information - headers already sent by (output started at /manager/processors/save_tmplvars.processor.php:223) in  /manager/processors/save_tmplvars.processor.php on line 168

Ошибки возникают после обновления с версии 1.4.20 до 1.4.23 и  с php 7.3 до 8,0

**Comment by exdis** [comment]
Спасибо за репорт. Однако этот репозиторий уже давно не поддерждивается и стоит его заархивировать. Совертую поискать другие более свежие форки MODx, либо использовать официальный репозиторий.
